-- ============================================================
--  SCHEMA SUPABASE — Portofolio V5 (Tozall)
--  Cara pakai: buka Supabase Dashboard > SQL Editor > New query,
--  paste SELURUH isi file ini, lalu klik RUN.
--  Aman dijalankan berulang (idempotent).
-- ============================================================

-- ------------------------------------------------------------
-- 1. TABEL
-- ------------------------------------------------------------

-- profiles: menyimpan role user. Dipakai Login.jsx & ProtectedRoute.jsx
create table if not exists public.profiles (
  id         uuid primary key references auth.users (id) on delete cascade,
  email      text,
  role       text not null default 'user',   -- 'admin' = boleh masuk /dashboard
  created_at timestamptz not null default now()
);

-- projects: dipakai Pages/Portofolio.jsx & Pages/dashboard/Projects.jsx
-- Nama kolom sengaja huruf besar (Title, Img, dst) mengikuti kode React.
create table if not exists public.projects (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  "Title"       text,
  "Description" text,
  "Img"         text,
  "TechStack"   text[] default '{}',
  "Features"    text[] default '{}',
  "Link"        text,
  "Github"      text
);

-- certificates: dipakai Pages/Portofolio.jsx & Pages/dashboard/Certificates.jsx
create table if not exists public.certificates (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  "Img"        text
);

-- portfolio_comments: dipakai components/Commentar.jsx & Pages/dashboard/Comments.jsx
create table if not exists public.portfolio_comments (
  id            uuid primary key default gen_random_uuid(),
  content       text not null,
  user_name     text not null,
  profile_image text,
  is_pinned     boolean not null default false,
  created_at    timestamptz not null default now()
);

create index if not exists portfolio_comments_pinned_idx
  on public.portfolio_comments (is_pinned, created_at desc);

-- ------------------------------------------------------------
-- 2. HELPER: cek admin
--    SECURITY DEFINER supaya policy tabel lain bisa memanggilnya
--    tanpa memicu rekursi RLS di tabel profiles.
-- ------------------------------------------------------------
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- ------------------------------------------------------------
-- 3. AUTO-BUAT PROFIL SAAT USER BARU DAFTAR
-- ------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ------------------------------------------------------------
-- 4. ROW LEVEL SECURITY
-- ------------------------------------------------------------
alter table public.profiles           enable row level security;
alter table public.projects           enable row level security;
alter table public.certificates       enable row level security;
alter table public.portfolio_comments enable row level security;

-- profiles ---------------------------------------------------
drop policy if exists "profil sendiri bisa dibaca"   on public.profiles;
drop policy if exists "admin baca semua profil"      on public.profiles;
drop policy if exists "admin ubah profil"            on public.profiles;

create policy "profil sendiri bisa dibaca" on public.profiles
  for select using (auth.uid() = id);

create policy "admin baca semua profil" on public.profiles
  for select using (public.is_admin());

create policy "admin ubah profil" on public.profiles
  for update using (public.is_admin()) with check (public.is_admin());

-- projects ---------------------------------------------------
drop policy if exists "projects boleh dibaca siapa saja" on public.projects;
drop policy if exists "projects ditulis admin"           on public.projects;

create policy "projects boleh dibaca siapa saja" on public.projects
  for select using (true);

create policy "projects ditulis admin" on public.projects
  for all using (public.is_admin()) with check (public.is_admin());

-- certificates -----------------------------------------------
drop policy if exists "certificates boleh dibaca siapa saja" on public.certificates;
drop policy if exists "certificates ditulis admin"           on public.certificates;

create policy "certificates boleh dibaca siapa saja" on public.certificates
  for select using (true);

create policy "certificates ditulis admin" on public.certificates
  for all using (public.is_admin()) with check (public.is_admin());

-- portfolio_comments -----------------------------------------
-- Komentar publik: siapa pun (anon) boleh baca & kirim,
-- tapi hanya admin yang boleh pin / hapus.
drop policy if exists "komentar boleh dibaca siapa saja" on public.portfolio_comments;
drop policy if exists "siapa saja boleh komentar"        on public.portfolio_comments;
drop policy if exists "admin pin komentar"               on public.portfolio_comments;
drop policy if exists "admin hapus komentar"             on public.portfolio_comments;

create policy "komentar boleh dibaca siapa saja" on public.portfolio_comments
  for select using (true);

create policy "siapa saja boleh komentar" on public.portfolio_comments
  for insert with check (is_pinned = false);

create policy "admin pin komentar" on public.portfolio_comments
  for update using (public.is_admin()) with check (public.is_admin());

create policy "admin hapus komentar" on public.portfolio_comments
  for delete using (public.is_admin());

-- ------------------------------------------------------------
-- 5. REALTIME (Commentar.jsx subscribe ke perubahan komentar)
-- ------------------------------------------------------------
do $$
begin
  alter publication supabase_realtime add table public.portfolio_comments;
exception
  when duplicate_object then null;
  when undefined_object then null;
end
$$;

-- ------------------------------------------------------------
-- 6. STORAGE BUCKET (semua public-read)
-- ------------------------------------------------------------
insert into storage.buckets (id, name, public) values
  ('project-images',     'project-images',     true),
  ('certificate-images', 'certificate-images', true),
  ('profile-images',     'profile-images',     true)
on conflict (id) do update set public = true;

drop policy if exists "bucket portofolio boleh dilihat publik" on storage.objects;
drop policy if exists "upload gambar project oleh admin"       on storage.objects;
drop policy if exists "upload foto profil oleh siapa saja"     on storage.objects;
drop policy if exists "admin hapus file"                       on storage.objects;

create policy "bucket portofolio boleh dilihat publik" on storage.objects
  for select using (
    bucket_id in ('project-images', 'certificate-images', 'profile-images')
  );

create policy "upload gambar project oleh admin" on storage.objects
  for insert with check (
    bucket_id in ('project-images', 'certificate-images') and public.is_admin()
  );

-- avatar komentar diunggah pengunjung anonim, jadi tidak butuh login
create policy "upload foto profil oleh siapa saja" on storage.objects
  for insert with check (bucket_id = 'profile-images');

create policy "admin hapus file" on storage.objects
  for delete using (
    bucket_id in ('project-images', 'certificate-images', 'profile-images')
    and public.is_admin()
  );

-- ============================================================
--  LANGKAH TERAKHIR — JADIKAN AKUNMU ADMIN
--  1) Authentication > Users > Add user > isi email + password
--     (centang "Auto Confirm User")
--  2) Jalankan query di bawah, ganti emailnya:
--
--     update public.profiles
--        set role = 'admin'
--      where email = 'email-kamu@contoh.com';
--
--  3) Cek hasilnya:  select id, email, role from public.profiles;
-- ============================================================
